[build]
	functions = "functions"
	command = "yarn build"
	publish = "out"

[dev]
  functions = "functions"
  publish   = "out"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects Next.js and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"