enum UserRole {
	ADMIN
	GUEST
	MEMBER
}

type User {
	username: String! @unique
  email: String! @unique
	favTeam: String
	leagues: [League] @relation
	role: UserRole
}

type League {
	name: String! @unique
	members: [User!] @relation
	options: LeagueOptions
	standings: [Standings] @relation
}

type Standings {
	member: User @relation
	points: Int
	league: League @relation
}

enum LeagueType {
	SINGLETEAM
	SINGLEDIVISION
	MULTITEAM
	MULTIDIVISION
	ANY
}

type Event {
	homeTeam: TeamType
	awayTeam: TeamType
	dateTime: String
	venue: String
	division: DivisionType
}

type TeamType {
	teamName: String
	teamId: String
	division: [DivisionType]
	badge: String
	country: String
}

type DivisionType {
	divisionId: String
	country: String
	teams: [TeamType]
	events: [Event]
}

type LeagueOptions {
	class: LeagueType
	divisions: [String]
	teams: [String]
	public: Boolean
}

type Query {
	allUsers: [User!]
	allLeagues: [League!]
}
