enum UserRole {
	ADMIN
	GUEST
	MEMBER
}

type User {
	username: String! @unique
  email: String! @unique
	favTeam: String
	leagues: [League] @relation
	role: UserRole
	guesses: [UserGuess]
}

type League {
	name: String! 
	slug: String! @unique
	members: [User] @relation
	options: LeagueOptions!
	standings: [Standings] @relation
}

type Standings {
	member: User @relation
	points: Int
	league: League @relation
}

enum LeagueType {
	SINGLETEAM
	SINGLEDIVISION
	MULTITEAM
	MULTIDIVISION
	ANY
}

type Event {
	eventId: String @unique
	lastUpdate: String
	homeTeamName: String
	awayTeamName: String
	homeTeamId: TeamType @relation(name: "home")
	awayTeamId: TeamType @relation(name: "away")
	dateTime: String
	venue: String
	divisionId: DivisionType
	divisionName: String
	submittedGuesses: [UserGuess] @relation
	finished: Boolean
}

enum WinnerEnum {
	HOMEWIN
	DRAW
	AWAYWIN
}

type UserGuess {
	eventId: Event @relation
	apiEventId: String
	user: User @relation
	score: [String]
	winner: WinnerEnum
	league: League @relation
	corrected: Boolean
}

type TeamType {
	teamId: String @unique
	teamName: String
	division: [DivisionType] @relation
	badge: String
	country: String
	homeEvents: [Event] @relation(name: "home")
	awayEvents: [Event] @relation(name: "away")
	inLeagues: [LeagueOptions]
}

type DivisionType {
	divisionId: String @unique
	divisionName: String
	country: String
	teams: [TeamType] @relation
	events: [Event] @relation
}

type LeagueOptions {
	class: LeagueType
	divisions: [String]
	teams: [TeamType]
	public: Boolean
}

type ResetRequest {
	email: String
	token: String
}

type Query {
	allUsers: [User!]
	allLeagues: [League]
	allEvents: [Event!]
	allTeams: [TeamType!]
	allGuesses: [UserGuess!]
	findLeague(slug: String!): League! @resolver(name: "findLeague", paginated: true)
	findGuessByUserId(user: ID!): [UserGuess!]! @resolver(name: "findGuessByUserId", paginated: true)
}
