enum UserRole {
	ADMIN
	GUEST
	MEMBER
}

type User {
	username: String! @unique
  email: String! @unique
	favTeam: String
	leagues: [League] @relation
	role: UserRole
}

type League {
	name: String! @unique
	members: [User!] @relation
	options: LeagueOptions
	standings: [Standings] @relation
}

type Standings {
	member: User @relation
	points: Int
	league: League @relation
}

enum LeagueType {
	SINGLETEAM
	SINGLEDIVISION
	MULTITEAM
	MULTIDIVISION
	ANY
}

type Event {
	homeTeamName: String
	awayTeamName: String
	homeTeamId: String
	awayTeamId: String
	dateTime: String
	venue: String
	divisionId: DivisionType
	divisionName: String
}

type TeamType {
	teamName: String
	teamId: String
	division: [DivisionType] @relation
	badge: String
	country: String
	events: [String]
}

type DivisionType {
	divisionId: String
	divisionName: String
	country: String
	teams: [TeamType] @relation
	events: [Event] @relation
}

type LeagueOptions {
	class: LeagueType
	divisions: [String]
	teams: [String]
	public: Boolean
}

type Query {
	allUsers: [User!]
	allLeagues: [League!]
	allEvents: [Event!]
}
