# curl --request GET \
# 	--url 'https://api-football-beta.p.rapidapi.com/fixtures?from=2021-02-11&to=2021-02-28&team=33&season=2020&league=39' \
# 	--header 'x-rapidapi-host: api-football-beta.p.rapidapi.com' \
# 	--header 'x-rapidapi-key: 6c47f2cfb6msh8e151b46675d508p1d39f3jsn66a99e015d81'

# curl --request GET \
# 	--url 'https://api-football-beta.p.rapidapi.com/teams?league=39&season=2020' \
# 	--header 'x-rapidapi-host: api-football-beta.p.rapidapi.com' \
# 	--header 'x-rapidapi-key: 6c47f2cfb6msh8e151b46675d508p1d39f3jsn66a99e015d81'

curl --request POST \
	--url 'http://localhost:3000/api/teams-import/'
	--header 'Content-Type: application/json' 
	--data "{ \"league\": \"2021\" }"